spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: <CLIENT_ID>
            client-secret: <CLIENT_SECRET>
#            provider: keycloak
#            authorization-grant-type: client_credentials
            scope: openid+email+profile
        provider:
          keycloak:
            issuer-uri: <ISSUER_URI>

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: TRACE
